spring:
  # Configuraciones específicas para desarrollo
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_platform_dev
    username: postgres
    password: postgres
    
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  flyway:
    clean-disabled: false # Permitir clean en dev, deshabilitar en prod
    
  # Configuración para DevTools
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
      
# Configuración más detallada para desarrollo
logging:
  level:
    root: INFO
    com.bookingsaas: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
# Configuración para almacenamiento temporal en desarrollo
app:
  storage:
    location: file:./uploads # Ubicación local para desarrollo
  feature-flags:
    loyalty-module: true
    payment-module: true
    notification-module: true
    document-module: false # Desactivado por defecto
    analytics-module: false # Desactivado por defecto
  auth:
    allow-mock: true # Permitir autenticación simulada para dev